# Hirad's tmux config

################################
# General
###############################

# use fish as default shell
set-option -g default-shell /opt/homebrew/bin/fish

# set first window to index 1
set -g base-index 1
set -g pane-base-index 1

# enable renaming window
setw -g automatic-rename on       # rename window to reflect current program
set -g renumber-windows on        # renumber windows when a window is closed

# way more history
set -g history-limit 100000

# enable mouse mode
set -g mouse on

# don't exit and instead go to last session on kill-session
set-option -g detach-on-destroy off

# set terminal title
set -g set-titles on

# neovim healcheck stuff
set-option -sg escape-time 10
set-option -g focus-events on

################################
# Style
###############################

# Colors
set -g default-terminal "tmux-256color"

set -g @black "#1a1a1a"
set -g @white "#fafafa"
set -g @orange "#f35815"
set -g @purple "#8467f3"
set -g @blue "#1e9de7"
set -g @green "#27b648"
set -g @yellow "#a78103"

# setw -g monitor-activity on

set -g status-bg '#1a1a1a'
# set -g window-style 'bg=#1a1a1a'
# set -g window-active-style 'bg=#1a1a1a'

# left status bar
set -g status-left-length 50
set -g status-left "#[fg=#{@black}]\ue0b6#[fg=#{@white},bg=#{@black}] #S #[fg=#{@black}]\ue0b6"

# center status bar
set -g status-justify centre
# current window - green background, black test
setw -g window-status-current-format "#[fg=#{@green},bg=#{@black}]\ue0b6#[fg=#{@black},bg=#{@green},bold]#I- #W -#F#[fg=#{@green},bg=#{@black}]\ue0b4"
# non-current window
setw -g window-status-format "#[fg=#{@black},bg=#{@black}]\ue0b6#[fg=#{@white},bg=#{@black},bold]#I- #W -#F#[fg=#{@black},bg=#{@black}]\ue0b4"

# right status bar
set-option -g status-right "#[fg=#{@black},bg=#{@orange}]\ue0b4#[fg=#282a36,bg=#{@orange}] #H #[fg=#{@orange},bg=#{@black}]\ue0b4"

################################
# Keybinds
###############################

# changing ctrl b to ctrl a as the prefix
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# PREFIX + r - easy config reload
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# PREFIX + f - sessionizer
bind-key -r f run-shell "tmux neww ~/code/hiradp/home/bin/tmux-sessionizer"

# PREFIX + ! - sessionizer in hiradp
bind-key -r ! run-shell "~/code/hiradp/home/bin/tmux-sessionizer ~/code/hiradp"

# PREFIX + @ - sessionizer in planetscale
bind-key -r @ run-shell "~/code/hiradp/home/bin/tmux-sessionizer ~/code/planetscale"

# PREFIX + L - switch to last session
bind-key L switch-client -l

# PREFIX + c - new window in current directory
bind c new-window -c "#{pane_current_path}"

# PREFIX + " - split down at 35%
bind-key '"' split-window -v -p 35 -c "#{pane_current_path}"

# PREFIX + % - split right in current directory
bind-key '%' split-window -h -c "#{pane_current_path}"

###############################
# Plugins
###############################

# download and install tpm if it's not installed
# install plugins by adding to the bottom of this file.
# https://github.com/tmux-plugins/tpm
if-shell "[ ! -d ~/.tmux/plugins/tpm ]" \
    'run-shell "mkdir -p ~/.tmux/plugins/tpm"; \
     run-shell "git clone https://github.com/tmux-plugins/tpm.git ~/.tmux/plugins/tpm"'

